### ISSUE TITLE
Call to a member function getName() on null

### ISSUE THREAD

**Issue by lingo** [digiaonline/graphql-php#353]
### What did you do?

Tried to query a simple schema that uses interfaces

### What did you expect to happen?

Expected to get results as indicated by GraphQL docs.

### What actually happened?

Got an error message:
```text
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [message] => Call to a member function getName() on null
                    [locations] => Array
                        (
                            [0] => Array
                                (
                                    [line] => 2
                                    [column] => 3
                                )

                        )

                    [path] => Array
                        (
                            [0] => test
                        )

                )

        )

    [data] => Array
        (
            [test] => 
        )

)
```

### What version of this project are you using?

v1.1.0

Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

**schema.sdl**
```sdl
interface NamedNode {
  """Each item must have an ID"""
  ID: ID!
  Name: String
}

type Test implements NamedNode {
  ID: ID!
  Name: String
  Message: String
}


"""What we can ask the server"""
type Query {

  """A simple test query"""
  test: NamedNode
}

schema {
  query: Query
}
```

-------------------------------------

```php
<?php
include_once "vendor/autoload.php";

use Digia\GraphQL\Language\FileSourceBuilder;
use function Digia\GraphQL\buildSchema;
use function Digia\GraphQL\graphql;

$queryText = <<<QUERY
{
  test {
    ID
    Name
    ...on Test {
      Message
    }
  }
}
QUERY;

$sourceBuilder = new FileSourceBuilder("schema.sdl");
$schema = buildSchema($sourceBuilder->build(), [
    'Query' => [
        'test' => function() {
            return [
                "Name" => "test",
                "Message" => "test message",
                "ID" => 1234
            ];
        },
    ]
]);

$result = graphql($schema, $queryText);
print_r($result);
```

**Comment by lingo** [comment]
I've dumped the stack trace out from within `graphql-php` code, to try to resolve this issue.
```
Call to a member function getName() on null

#0 /var/www/html/vendor/digiaonline/graphql/src/Execution/Strategy/AbstractExecutionStrategy.php(764): Digia\GraphQL\Execution\Strategy\AbstractExecutionStrategy->buildLocatedError(Object(Error), Array, Array)
#1 /var/www/html/vendor/digiaonline/graphql/src/Execution/Strategy/AbstractExecutionStrategy.php(345): Digia\GraphQL\Execution\Strategy\AbstractExecutionStrategy->handleFieldError(Object(Error), Array, Array, Object(Digia\GraphQL\Type\Definition\InterfaceType))
#2 /var/www/html/vendor/digiaonline/graphql/src/Execution/Strategy/AbstractExecutionStrategy.php(219): Digia\GraphQL\Execution\Strategy\AbstractExecutionStrategy->completeValueCatchingError(Object(Digia\GraphQL\Type\Definition\InterfaceType), Array, Object(Digia\GraphQL\Execution\ResolveInfo), Array, Array)
#3 /var/www/html/vendor/digiaonline/graphql/src/Execution/Strategy/ParallelExecutionStrategy.php(34): Digia\GraphQL\Execution\Strategy\AbstractExecutionStrategy->resolveField(Object(Digia\GraphQL\Type\Definition\ObjectType), NULL, Array, Array)
#4 /var/www/html/vendor/digiaonline/graphql/src/Execution/Strategy/AbstractExecutionStrategy.php(125): Digia\GraphQL\Execution\Strategy\ParallelExecutionStrategy->executeFields(Object(Digia\GraphQL\Type\Definition\ObjectType), NULL, Array, Array)
#5 /var/www/html/vendor/digiaonline/graphql/src/Execution/Execution.php(90): Digia\GraphQL\Execution\Strategy\AbstractExecutionStrategy->execute()
#6 /var/www/html/vendor/digiaonline/graphql/src/Execution/Execution.php(53): Digia\GraphQL\Execution\Execution->executeOperation(NULL, Object(Digia\GraphQL\Execution\ExecutionContext), Object(Digia\GraphQL\Execution\Strategy\FieldCollector), Object(Digia\GraphQL\Execution\ValuesResolver))
#7 /var/www/html/vendor/digiaonline/graphql/src/GraphQL.php(266): Digia\GraphQL\Execution\Execution->execute(Object(Digia\GraphQL\Schema\Schema), Object(Digia\GraphQL\Language\Node\DocumentNode), NULL, NULL, Array, NULL, NULL, NULL)
#8 /var/www/html/vendor/digiaonline/graphql/src/api.php(151): Digia\GraphQL\GraphQL::execute(Object(Digia\GraphQL\Schema\Schema), Object(Digia\GraphQL\Language\Node\DocumentNode), NULL, NULL, Array, NULL, NULL, NULL)
#9 /var/www/html/vendor/digiaonline/graphql/src/GraphQL.php(335): Digia\GraphQL\execute(Object(Digia\GraphQL\Schema\Schema), Object(Digia\GraphQL\Language\Node\DocumentNode), NULL, NULL, Array, NULL, NULL, NULL)
#10 /var/www/html/vendor/digiaonline/graphql/src/api.php(199): Digia\GraphQL\GraphQL::process(Object(Digia\GraphQL\Schema\Schema), 'query {\n  test(...', NULL, NULL, Array, NULL, NULL, NULL)
#11 /var/www/html/gqltest.php(33): Digia\GraphQL\graphql(Object(Digia\GraphQL\Schema\Schema), 'query {\n  test(...')
#12 {main}
```

**Comment by lingo** [comment]
I have found eventually that I can make this code work by adding the following code:

```diff
--- gqltest.php	2020-01-18 20:47:56.050542861 +1300
+++ gqltest2.php	2020-01-18 20:47:43.210501306 +1300
@@ -28,6 +28,11 @@
             ];
         },
     ],
+    'NamedNode' => [
+        '__resolveType' => function($item) {
+            return 'Test';
+        },
+    ],
 ]);
 
 $result = graphql($schema, $queryText);
```
